name: l3a
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h5eee18b_3
  - cryptography=38.0.2=py37h5994e8b_1
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.30=py37hd23a5d3_0
  - ffmpeg=4.3=hf484d3e_0
  - fonttools=4.38.0=py37h540881e_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=16_linux64_mkl
  - libdeflate=1.8=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=16_linux64_mkl
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.43=h2797004_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.2=py37hc347a89_0
  - mkl=2022.1.0=hc2b9512_224
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=h7d73246_0
  - openssl=3.3.2=hb9d3cd8_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycocotools=2.0.4=py37hda87dfa_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=py37_1
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.11.0=py37_cu113
  - torchvision=0.12.0=py37_cu113
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - unicodedata2=14.0.0=py37h540881e_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - astroid==2.15.8
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==24.2.0
      - cachetools==5.5.0
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - continuum==1.2.3
      - datasets==2.13.2
      - dill==0.3.6
      - dodgy==0.2.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - filelock==3.12.2
      - flake8==5.0.4
      - flake8-polyfill==1.0.2
      - flashtorch==0.1.3
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.35.0
      - google-auth-oauthlib==0.4.6
      - grad-cam==1.4.8
      - grpcio==1.62.3
      - h5py==3.8.0
      - huggingface-hub==0.16.4
      - idna==3.10
      - imagehash==4.3.1
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - inplace-abn==1.1.0
      - isort==5.11.5
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-object-proxy==1.9.0
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.1
      - mccabe==0.7.0
      - multidict==6.0.5
      - multiprocess==0.70.14
      - mypy==1.4.1
      - mypy-extensions==1.0.0
      - networkx==2.6.3
      - numpy==1.21.5
      - oauthlib==3.2.2
      - objprint==0.2.3
      - opencv-python==4.5.5.64
      - openpyxl==3.1.3
      - packaging==24.0
      - pandas==1.3.5
      - pep8-naming==0.10.0
      - pillow==9.3.0
      - pip==24.0
      - platformdirs==4.0.0
      - pluggy==1.2.0
      - prospector==1.10.3
      - protobuf==3.20.3
      - pyarrow==12.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycodestyle==2.9.1
      - pydocstyle==6.3.0
      - pyflakes==2.5.0
      - pylint==2.17.7
      - pylint-celery==0.3
      - pylint-django==2.5.3
      - pylint-flask==0.6
      - pylint-plugin-utils==0.7
      - pytest==7.4.4
      - pytest-mock==3.11.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywavelets==1.3.0
      - pyyaml==6.0
      - randaugment==1.0.2
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - requirements-detector==1.2.2
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - semver==3.0.2
      - setoptconf-tmp==0.3.1
      - setuptools==68.0.0
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==1.1.0
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - timm==0.5.4
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.12.5
      - torchmetrics==0.11.4
      - tqdm==4.66.5
      - ttach==0.0.3
      - typed-ast==1.5.5
      - urllib3==2.0.7
      - viztracer==0.15.6
      - werkzeug==2.2.3
      - wheel==0.42.0
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yarl==1.9.4
      - zipp==3.15.0
