# arch
arch: l3a
excel_path: l3a_coco.xlsx

# datasets
root_dir:  # your coco dataset path
dataset_name: coco2014
image_size: 224

# training
base_lr: 0.00004
lr: 0.0001
weight_decay: 0.0001
epochs: 1
batch_size: 64
num_workers: 16

# model
model_name: tresnet_m
pretrained_path: pretrained_models/tresnet_m_224_21k.pth

# incremental
total_classes: 80
base_classes: 40
task_size: 10

# L3A specific
recurbase: False
Hidden: 4096
repeat: 1
rg: 1000
rectifier_fac: True

pseudo_label: True
thre: 0.7

resume:
resume_low_range: 40

# outputs
logger_dir: logger
tensorboard_dir: tensorboard
save_model: False
model_save_path: saved_models
